# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 Instance and a Security Group to allow SSH

Resources:

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: key-pair
      ImageId: 'ami-06878d265978313ca' 
      InstanceType: t2.micro

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0