defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

version: 2.1

jobs:
  create_infrastructure:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm run lint


workflows:
  CI_workflow:
    jobs:
      - create_infrastructure